language: rust
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install libXxf86vm-dev cmake libsdl2-dev
script:
  - (cd gfx_cube && cargo build -v)
  - (cd image && cargo build -v)
  - (cd paint && cargo build -v)
  - (cd deform && cargo build -v)
  - (cd user_input && cargo build -v)
  - (cd sprite && cargo build -v)
  - (cd freetype && cargo build -v)
