[package]
name = "piston-examples"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"

[[bin]]
name = "draw_state"
path = "src/draw_state.rs"

[dependencies]
piston_window = "0.5.0"
find_folder = "0.2.0"
