[package]
name = "piston-example-gfx_graphics_examples"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[[bin]]
name = "draw_state_test"
path = "src/draw_state_test.rs"

[[bin]]
name = "text_test"
path = "src/text_test.rs"

[dependencies]
piston_window = "0.5.0"

