[package]
name = "piston-example-freetype"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[[bin]]
name = "piston-example-freetype"
path = "src/main.rs"

[dependencies]
piston = "0.9.0"
piston2d-opengl_graphics = "0.6.0"
piston2d-graphics = "0.4.1"
pistoncore-sdl2_window = "0.11.0"
freetype-rs = "0.2.1"
find_folder = "0.2.0"
