[package]
name = "piston-example-user_input"
version = "0.0.0"
authors = ["Your Name <your@email.com>"]
keywords = []

[[bin]]
name = "piston-example-user_input"
path = "src/main.rs"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"
optional = true

[dependencies.pistoncore-glfw_window]
git = "https://github.com/pistondevelopers/glfw_window"
optional = true

[dependencies.pistoncore-glutin_window]
git = "https://github.com/pistondevelopers/glutin_window"
optional = true

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"

[dependencies.piston2d-opengl_graphics]
git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"

[features]
default = ["include_glfw"]
include_sdl2 = ["pistoncore-sdl2_window"]
include_glfw = ["pistoncore-glfw_window"]
include_glutin = ["pistoncore-glutin_window"]

### Workaround rustc ICE ###
[profile.dev]
debug = false
############################
