[package]

name = "piston-example-user_input"
version = "0.0.0"
authors = ["Your Name <your@email.com>"]
tags = []

[[bin]]

name = "piston-example-user_input"
path = "src/main.rs"

[dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"

[dependencies.pistoncore-window]
git = "https://github.com/PistonDevelopers/window"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.pistoncore-glfw_window]
git = "https://github.com/PistonDevelopers/glfw_window"

[dependencies.pistoncore-input]
git = "https://github.com/pistondevelopers/input"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"

[dependencies.quack]
git = "https://github.com/pistondevelopers/quack"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"

