[package]

name = "paint"
version = "0.0.1"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]

[[bin]]

name = "piston-example-paint"
path = "src/main.rs"

[dependencies.sdl2_game_window]

git = "https://github.com/pistondevelopers/sdl2_game_window"

[dependencies.opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

